const images = {
  Spalsh_Logo: require('./one_fifty.png'),
  App_Logo: require('./one_fifty.png'),
  Swiper_First: require('./LottieAnimation/GetSliderOne.json'),
  Swiper_Two: require('./LottieAnimation/GetSlidertwo.json'),
  Swiper_Three: require('./LottieAnimation/GetSliderthree.json'),
  //   Swiper_Three: require('./LottieAnimation/GetSliderthree.json'),
  Languageanimation: require('./LottieAnimation/languageanimation.json'),
  Account_created: require('./LottieAnimation/Accountcreated.json'),
  Congratulation_Animation: require('./LottieAnimation/Congratulation.json'),
  Reviewsimage_screen: require('./LottieAnimation/Reviewsimage.json'),
  Color_Picker_Image: require('./colorpickernew.png'),
  User_image_one_profile: require('./one_fifty.png'),
  Home_First_Slide_Image_1: require('./TwoHundred.png'),
  Home_First_Slide_Image_2: require('./TwoHundred.png'),
  Home_First_Slide_Image_3: require('./TwoHundred.png'),
  Home_First_Slide_Image_4: require('./TwoHundred.png'),
  Home_First_Slide_Image_5: require('./TwoHundred.png'),
  // two slider home
  Home_First_Slide_Image_7: require('./one_fifty.png'),
  Home_First_Slide_Image_8: require('./one_fifty.png'),
  Home_First_Slide_Image_9: require('./one_fifty.png'),
  Home_First_Slide_Image_10: require('./one_fifty.png'),
  Home_First_Slide_Image_11: require('./one_fifty.png'),
  Home_First_Slide_Image_12: require('./one_fifty.png'),
  Home_First_Slide_Image_13: require('./one_fifty.png'),
  // Popular Courses
  Home_First_Slide_Image_14: require('./TwoHundred.png'),
  Home_First_Slide_Image_15: require('./TwoHundred.png'),
  Home_First_Slide_Image_16: require('./TwoHundred.png'),
  Home_First_Slide_Image_17: require('./TwoHundred.png'),
  // New Courses
  Home_First_Slide_Image_18: require('./TwoHundred.png'),
  Home_First_Slide_Image_19: require('./TwoHundred.png'),
  Home_First_Slide_Image_20: require('./TwoHundred.png'),
  Home_First_Slide_Image_21: require('./TwoHundred.png'),
  // Instructor
  Home_First_Slide_Image_22: require('./hundred.png'),
  Home_First_Slide_Image_23: require('./hundred.png'),
  Home_First_Slide_Image_24: require('./hundred.png'),
  Home_First_Slide_Image_25: require('./hundred.png'),
  Home_First_Slide_Image_26: require('./hundred.png'),
  // My Courses
  My_Courses_Image_1: require('./one_fifty.png'),
  My_Courses_Image_2: require('./one_fifty.png'),
  My_Courses_Image_3: require('./one_fifty.png'),
  My_Courses_Image_4: require('./one_fifty.png'),
  My_Courses_Image_5: require('./one_fifty.png'),
  My_Courses_Image_6: require('./one_fifty.png'),
  My_Courses_Image_7: require('./one_fifty.png'),
  My_Courses_Image_8: require('./one_fifty.png'),
  // videocall image
  speker_off: require('./spekeroff.png'),
  speker_on: require('./spekeron.png'),
  videocall_one_img: require('./FortyFive.png'),
  videocall_two_img: require('./FortyFive.png'),
  videocall_three_img: require('./FortyFive.png'),
  videocall_four_img: require('./FortyFive.png'),
  videocall_four_img_like: require('./likeimage.png'),
  videocall_five_img: require('./graphimage.png'),
  videocall_six_img: require('./FortyFive.png'),
  videocall_saven_img: require('./FortyFive.png'),
  videocall_aeight_img: require('./FortyFive.png'),
  videocall_aeight_img_two: require('./FortyFive.png'),
  // Instructer image
  Profile_Image: require('./one_fifty.png'),
  Course_Image_1: require('./one_fifty.png'),
  Course_Image_2: require('./one_fifty.png'),
  // Instructer image
  Courses_details_image_1: require('./one_fifty.png'),
  // Courses Details image
  Description_image_1: require('./one_fifty.png'),
  Description_image_2: require('./one_fifty.png'),
  Description_image_3: require('./one_fifty.png'),
  Description_image_4: require('./one_fifty.png'),
  Description_image_5: require('./one_fifty.png'),
  //   Description_image_5: require('./one_fifty.png'),
  // Reviews Tab Image
  Reviews_Image_1: require('./30x30.png'),
  Reviews_Image_2: require('./30x30.png'),
  Reviews_Image_3: require('./30x30.png'),
  Reviews_Image_4: require('./30x30.png'),
  Reviews_Image_5: require('./30x30.png'),
  Buy_Courses_Image: require('./TwoHundred.png'),
  // paymet image
  Paymrny_Image_1: require('./icon_point.png'),
  Paymrny_Image_2: require('./icon_gpay.png'),
  Paymrny_Image_3: require('./paypallogo.png'),
  Crideit_card: require('./creditcardimage.png'),
  Searchbg_Image: require('./TwoHundred.png'),
  Successfully_Images: require('./one_fifty.png'),
};
export default images;
